config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  resources :topics do
    resources :bookmarks, except: [:index] do
     resources :likes, only: [:create, :destroy]
   end
  end 
  

  devise_for :users
    resources :users, only: [:show]
  
  get 'welcome/index'

  get 'welcome/about'

  root to: 'welcome#index'
  post :incoming, to: 'incoming#create'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy

  extend FriendlyId
  friendly_id :url, use: :slugged

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics
  has_many :likes, dependent: :destroy
  has_many :bookmarks
  def liked(bookmark)
     likes.where(bookmark_id: bookmark.id).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
     before_action :configure_permitted_parameters, if: :devise_controller?
 
 rescue_from Pundit::NotAuthorizedError do |exception|
  redirect_to root_url, alert: "Not allowed to view content"
end

   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :username
   end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def show
   @topic = Topic.find(params[:topic_id])
   @bookmark = Bookmark.friendly.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
    authorize @bookmark
  end

  def create
    @topic = Topic.find(params[:topic_id])  
    @bookmark_total = @topic.bookmarks.count 
    @bookmark = @topic.bookmarks.find_or_create_by(bookmark_params)
    @bookmark.update_attributes(user_id: current_user.id)
    authorize @bookmark
    if @bookmark_total == @topic.bookmarks.count
      flash[:notice] = "You already have this Bookmark."
      redirect_to @topic
    else
      flash[:notice] = "Bookmark was created." 
      redirect_to @topic
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end

def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])  
    @bookmark.update_attributes(bookmark_params)
    redirect_to @topic
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    
    @bookmark.destroy
    redirect_to @topic
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:url)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    # Take a look at these in your server logs
    # to get a sense of what you're dealing with.
    Rails.logger.info "INCOMING PARAMS HERE: #{params}"

    # You put the message-splitting and business
    # magic here. 
    
     # Find the user by using params[:sender]
     @user = User.find_by_email(params[:sender])

     # Find the topic by using params[:subject]
     @topic = Topic.find_by_title(params[:subject])

     # Assign the url to a variable after retreiving it from params["body-plain"]
     @url = params[:"body-plain"]

     # Check if user is nil, if so, create and save a new user
     from = params[:from]
     if @user.nil?
        @user = User.create(:username => from.slice(0..((from.index('<')-2))), :email => params[:sender])
     end
       

     # Check if the topic is nil, if so, create and save a new topic
     if @topic.nil?
        topic = params[:subject]
        @topic = Topic.create(title: topic, user_id: @user.id)
     end

     # Now that you're sure you have a valid user and topic, build and save a new bookmark
     @bookmark = Bookmark.create(:url => @url, :topic => @topic)

    # Assuming all went well. 
    head 200
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 def create
   @bookmark = Bookmark.find(params[:bookmark_id])
   like = current_user.likes.build(bookmark: @bookmark)
   authorize like

   if like.save
       # Add code to generate a success flash and redirect to @bookmark
       redirect_to :back, notice:"Liked."
     else
       # Add code to generate a failure flash and redirect to @bookmark
       redirect_to :back, notice: "Failed to Like this bookmark"
     end
   end

   def destroy
     @bookmark = Bookmark.find(params[:bookmark_id])
     like = current_user.likes.find(params[:id])
     authorize like
     
     if like.destroy
       # Flash success and redirect to @bookmark
       redirect_to :back, notice: "Unliked"
     else
       # Flash error and redirect to @bookmark
       redirect_to :back, notice: "Failed to unlike this bookmark"
     end
   end
 end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    authorize @topics
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    @topic.save
    redirect_to topics_path
  end

  def edit
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  private
    def topic_params
      params.require(:topic).permit(:title)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @user = current_user
     @bookmarks = @user.bookmarks
     @likes = @user.likes
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_form.html.erb
 <div class="row">
   <div class="col-md-8">
     <%= form_for [@topic, @bookmark] do |b| %>
       <div class="form-group">
         <%= b.label :url %>
         <%= b.text_field :url, class: 'form-control', placeholder: "Enter bookmark url" %>
       </div>
       <div class="form-group">
         <%= b.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>
 <%= render partial: 'form', locals: { topic: @topic, post: @bookmark } %>

app/views/bookmarks/new.html.erb
 <h1>New Bookmark</h1>

 <%= render partial: 'form', locals: { topic: @topic, post: @bookmark } %>

app/views/bookmarks/show.html.erb
<h1><%= link_to @bookmark.url, "http://#{@bookmark.url}", :target => "_blank" %>   </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blockmarks</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    
    <ul class="nav nav-tabs">
     <li><%= link_to "Blockmarks", topics_path %></li>
     <li><%= link_to "My Profile", users_show_path %></li>

     <div class="pull-right user-info">
       <% if current_user %>
       Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
       <% else %>
       <%= link_to "Sign In", new_user_session_path %> or
       <%= link_to "Sign Up", new_user_registration_path %>
       <% end %>
     </div>
   </ul>
   
   <% if flash[:notice] %>
   
   <div class="alert alert-success">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
     <%= flash[:notice] %>
   </div>
   <% elsif flash[:error] %>
   <div class="alert alert-danger">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
     <%= flash[:error] %>
   </div>
   <% elsif flash[:alert] %>
   <div class="alert alert-warning">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
     <%= flash[:alert] %>
   </div>
   
   <% end %>
       
   <%= yield %>
   
 </div>

</body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
    <% if like = current_user.liked(bookmark) %>
      <%= link_to [bookmark.topic, bookmark, like], class: 'btn btn-danger btn-xs', method: :delete do %>
      <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
    <% end %>
    <% else %>
      <%= link_to [bookmark.topic, bookmark, Like.new], class: 'btn btn-primary btn-xs', method: :post do %>
      <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
    <% end %>
<% end %>
<% end %>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<div class="row">
  <div class="col-md-2">
    <h1>Topics</h1>
  </div>
  <div class="col-md-2">
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success btn-sm' %>
  </div>
</div>

<% @topics.each do |topic| %>
<div class="row">
        
      <div class="col-md-1">
        <h4><%= link_to topic.title, topic_path(topic) %></h4>
      </div> 

      <div class="col-md-1">
        <h5>by:<%= topic.user.username %></h5>
      </div>
           
      <% if policy(topic).destroy? %>
        <div class="col-md-1">
          <%= link_to 'Delete', topic, method: :delete, class: 'btn btn-danger btn-xs' %>
        </div>     
      <% end %>
</div>
<% end %>

app/views/topics/new.html.erb
 <h1>New Topic</h1>
 
 <div class="row">
   <div class="col-md-8">
     <%= form_for @topic do |t| %>
       <div class="form-group">
         <%= t.label :title %>
         <%= t.text_field :title, class: 'form-control', placeholder: "Enter topic title" %>
       </div>
       <div class="form-group">
         <%= t.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
    <% if policy(@topic).update? %>
    <%= link_to "New Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success btn-sm' %>
    <% end %>
<div class="row">
  <div class="col-md-8">
    <% @topic.bookmarks.each do |b| %>
    
      <div class="col-md-4">
                                       
      <%= link_to b.url, [b.topic, b] %> 
              
      <% if policy(b.topic).destroy? %>
      <%= link_to '', [b.topic, b], method: :delete, class: 'glyphicon glyphicon-trash' %>
      <% end %>

      <% if policy(b.topic).update? %>
      <%= link_to '', edit_topic_bookmark_path(b.topic, b), class: 'glyphicon glyphicon-edit' %>
      <% end %>

      <%= render partial: 'likes/like', locals: { bookmark: b } %>

      </div>
    <% end %>
  </div>
 </div> 

app/views/users/show.html.erb
<h1>My BlockMarks</h1>
<div class="row">
  <div class="col-md-8">
<% @bookmarks.each do |bookmark| %>
  <div class="col-md-4">
    <%= link_to bookmark.url, "http://#{bookmark.url}" %>  
  </div>
<% end %>
 </div>
 </div> 

 <h1>My Likes</h1>
<div class="row">
  <div class="col-md-8">
<% @likes.each do |like| %>
  <div class="col-md-4">
    <%= link_to like.bookmark.url, "http://#{like.bookmark.url}" %> 
    <%= render partial: 'likes/like', locals: { bookmark: like.bookmark } %>
  </div>
<% end %>
 </div>
 </div> 

app/views/welcome/about.html.erb
<h1>Welcome</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>